# permissions for end users to view clickhousebackups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clickhousebackup-viewer-role
rules:
- apiGroups:
  - backups.sputnik.systems
  resources:
  - clickhousebackups
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - backups.sputnik.systems
  resources:
  - clickhousebackups/status
  verbs:
  - get
