# permissions for end users to view clickhousebackupschedules.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clickhousebackupschedule-viewer-role
rules:
- apiGroups:
  - backups.sputnik.systems
  resources:
  - clickhousebackupschedules
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - backups.sputnik.systems
  resources:
  - clickhousebackupschedules/status
  verbs:
  - get
