# permissions for end users to edit clickhousebackupschedules.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clickhousebackupschedule-editor-role
rules:
- apiGroups:
  - backups.sputnik.systems
  resources:
  - clickhousebackupschedules
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - backups.sputnik.systems
  resources:
  - clickhousebackupschedules/status
  verbs:
  - get
