# permissions for end users to edit dgraphbackups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dgraphbackup-editor-role
rules:
- apiGroups:
  - backups.sputnik.systems
  resources:
  - dgraphbackups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - backups.sputnik.systems
  resources:
  - dgraphbackups/status
  verbs:
  - get
