# permissions for end users to view dgraphbackupschedules.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dgraphbackupschedule-viewer-role
rules:
- apiGroups:
  - backups.sputnik.systems
  resources:
  - dgraphbackupschedules
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - backups.sputnik.systems
  resources:
  - dgraphbackupschedules/status
  verbs:
  - get
