
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - backups.sputnik.systems
  resources:
  - dgraphbackups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - backups.sputnik.systems
  resources:
  - dgraphbackups/finalizers
  verbs:
  - update
- apiGroups:
  - backups.sputnik.systems
  resources:
  - dgraphbackups/status
  verbs:
  - get
  - patch
  - update
