apiVersion: backups.sputnik.systems/v1alpha1
kind: DgraphBackupSchedule
metadata:
  name: default
spec:
  schedule: "*/10 * * * *"
  backup:
    adminUrl: http://dgraph-dgraph-alpha:8080/admin
    destination: s3://s3.us-east-2.amazonaws.com/dgraph-test
    region: us-east-2
    secrets:
      - dgraph-backup-s3-creds
