apiVersion: backups.sputnik.systems/v1alpha1
kind: DgraphBackupSchedule
metadata:
  name: default
spec:
  schedule: "*/10 * * * *"
  backup:
    adminUrl: http://dgraph-dgraph-alpha:8080/admin
    destination: minio://storage.yandexcloud.net/sputnik-systems-backups/dgraph/staging-services
    region: ru-central1
    secrets:
      - dgraph-yandex-cloud-s3
