apiVersion: backups.sputnik.systems/v1alpha1
kind: DgraphBackupSchedule
metadata:
  name: default
spec:
  schedule: "*/10 * * * *"
  retention: 45m
  backup:
    adminUrl: http://dgraph-dgraph-alpha:8080/admin
    destination: s3://s3.eu-north-1.amazonaws.com/dgraph-test
    region: eu-north-1
    secrets:
      - dgraph-backup-s3-creds
